// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: trip.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GeoLocation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      float64                `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeoLocation) Reset() {
	*x = GeoLocation{}
	mi := &file_trip_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeoLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeoLocation) ProtoMessage() {}

func (x *GeoLocation) ProtoReflect() protoreflect.Message {
	mi := &file_trip_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeoLocation.ProtoReflect.Descriptor instead.
func (*GeoLocation) Descriptor() ([]byte, []int) {
	return file_trip_proto_rawDescGZIP(), []int{0}
}

func (x *GeoLocation) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *GeoLocation) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *GeoLocation) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type FareDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AmountInCents int64                  `protobuf:"varint,1,opt,name=amount_in_cents,json=amountInCents,proto3" json:"amount_in_cents,omitempty"`
	Currency      string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FareDetails) Reset() {
	*x = FareDetails{}
	mi := &file_trip_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FareDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FareDetails) ProtoMessage() {}

func (x *FareDetails) ProtoReflect() protoreflect.Message {
	mi := &file_trip_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FareDetails.ProtoReflect.Descriptor instead.
func (*FareDetails) Descriptor() ([]byte, []int) {
	return file_trip_proto_rawDescGZIP(), []int{1}
}

func (x *FareDetails) GetAmountInCents() int64 {
	if x != nil {
		return x.AmountInCents
	}
	return 0
}

func (x *FareDetails) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type AcceptTripDriverRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TripId        string                 `protobuf:"bytes,1,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	RiderId       string                 `protobuf:"bytes,3,opt,name=rider_id,json=riderId,proto3" json:"rider_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptTripDriverRequest) Reset() {
	*x = AcceptTripDriverRequest{}
	mi := &file_trip_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptTripDriverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptTripDriverRequest) ProtoMessage() {}

func (x *AcceptTripDriverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trip_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptTripDriverRequest.ProtoReflect.Descriptor instead.
func (*AcceptTripDriverRequest) Descriptor() ([]byte, []int) {
	return file_trip_proto_rawDescGZIP(), []int{2}
}

func (x *AcceptTripDriverRequest) GetTripId() string {
	if x != nil {
		return x.TripId
	}
	return ""
}

func (x *AcceptTripDriverRequest) GetRiderId() string {
	if x != nil {
		return x.RiderId
	}
	return ""
}

type AcceptTripDriverResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TripId        string                 `protobuf:"bytes,1,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptTripDriverResponse) Reset() {
	*x = AcceptTripDriverResponse{}
	mi := &file_trip_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptTripDriverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptTripDriverResponse) ProtoMessage() {}

func (x *AcceptTripDriverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trip_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptTripDriverResponse.ProtoReflect.Descriptor instead.
func (*AcceptTripDriverResponse) Descriptor() ([]byte, []int) {
	return file_trip_proto_rawDescGZIP(), []int{3}
}

func (x *AcceptTripDriverResponse) GetTripId() string {
	if x != nil {
		return x.TripId
	}
	return ""
}

func (x *AcceptTripDriverResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AcceptTripDriverResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RideDetails struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DurationSeconds int64                  `protobuf:"varint,1,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	DistanceMetrs   int64                  `protobuf:"varint,2,opt,name=distance_metrs,json=distanceMetrs,proto3" json:"distance_metrs,omitempty"`
	Status          string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RideDetails) Reset() {
	*x = RideDetails{}
	mi := &file_trip_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RideDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RideDetails) ProtoMessage() {}

func (x *RideDetails) ProtoReflect() protoreflect.Message {
	mi := &file_trip_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RideDetails.ProtoReflect.Descriptor instead.
func (*RideDetails) Descriptor() ([]byte, []int) {
	return file_trip_proto_rawDescGZIP(), []int{4}
}

func (x *RideDetails) GetDurationSeconds() int64 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *RideDetails) GetDistanceMetrs() int64 {
	if x != nil {
		return x.DistanceMetrs
	}
	return 0
}

func (x *RideDetails) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetActiveTripRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActiveTripRequest) Reset() {
	*x = GetActiveTripRequest{}
	mi := &file_trip_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActiveTripRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActiveTripRequest) ProtoMessage() {}

func (x *GetActiveTripRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trip_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActiveTripRequest.ProtoReflect.Descriptor instead.
func (*GetActiveTripRequest) Descriptor() ([]byte, []int) {
	return file_trip_proto_rawDescGZIP(), []int{5}
}

type GetActiveTripResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pickup        *GeoLocation           `protobuf:"bytes,1,opt,name=pickup,proto3" json:"pickup,omitempty"`
	Dropoff       *GeoLocation           `protobuf:"bytes,2,opt,name=dropoff,proto3" json:"dropoff,omitempty"`
	RideDetails   *RideDetails           `protobuf:"bytes,3,opt,name=ride_details,json=rideDetails,proto3" json:"ride_details,omitempty"`
	DriverFare    float32                `protobuf:"fixed32,4,opt,name=driver_fare,json=driverFare,proto3" json:"driver_fare,omitempty"`
	RiderId       string                 `protobuf:"bytes,5,opt,name=rider_id,json=riderId,proto3" json:"rider_id,omitempty"`
	TripId        string                 `protobuf:"bytes,6,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActiveTripResponse) Reset() {
	*x = GetActiveTripResponse{}
	mi := &file_trip_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActiveTripResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActiveTripResponse) ProtoMessage() {}

func (x *GetActiveTripResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trip_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActiveTripResponse.ProtoReflect.Descriptor instead.
func (*GetActiveTripResponse) Descriptor() ([]byte, []int) {
	return file_trip_proto_rawDescGZIP(), []int{6}
}

func (x *GetActiveTripResponse) GetPickup() *GeoLocation {
	if x != nil {
		return x.Pickup
	}
	return nil
}

func (x *GetActiveTripResponse) GetDropoff() *GeoLocation {
	if x != nil {
		return x.Dropoff
	}
	return nil
}

func (x *GetActiveTripResponse) GetRideDetails() *RideDetails {
	if x != nil {
		return x.RideDetails
	}
	return nil
}

func (x *GetActiveTripResponse) GetDriverFare() float32 {
	if x != nil {
		return x.DriverFare
	}
	return 0
}

func (x *GetActiveTripResponse) GetRiderId() string {
	if x != nil {
		return x.RiderId
	}
	return ""
}

func (x *GetActiveTripResponse) GetTripId() string {
	if x != nil {
		return x.TripId
	}
	return ""
}

type CancelTripRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TripId        string                 `protobuf:"bytes,1,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	DriverId      string                 `protobuf:"bytes,3,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	RiderId       string                 `protobuf:"bytes,4,opt,name=rider_id,json=riderId,proto3" json:"rider_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTripRequest) Reset() {
	*x = CancelTripRequest{}
	mi := &file_trip_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTripRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTripRequest) ProtoMessage() {}

func (x *CancelTripRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trip_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTripRequest.ProtoReflect.Descriptor instead.
func (*CancelTripRequest) Descriptor() ([]byte, []int) {
	return file_trip_proto_rawDescGZIP(), []int{7}
}

func (x *CancelTripRequest) GetTripId() string {
	if x != nil {
		return x.TripId
	}
	return ""
}

func (x *CancelTripRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *CancelTripRequest) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *CancelTripRequest) GetRiderId() string {
	if x != nil {
		return x.RiderId
	}
	return ""
}

type CancelTripResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	TripId        string                 `protobuf:"bytes,2,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	IsSuccess     bool                   `protobuf:"varint,3,opt,name=is_success,json=isSuccess,proto3" json:"is_success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTripResponse) Reset() {
	*x = CancelTripResponse{}
	mi := &file_trip_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTripResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTripResponse) ProtoMessage() {}

func (x *CancelTripResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trip_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTripResponse.ProtoReflect.Descriptor instead.
func (*CancelTripResponse) Descriptor() ([]byte, []int) {
	return file_trip_proto_rawDescGZIP(), []int{8}
}

func (x *CancelTripResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CancelTripResponse) GetTripId() string {
	if x != nil {
		return x.TripId
	}
	return ""
}

func (x *CancelTripResponse) GetIsSuccess() bool {
	if x != nil {
		return x.IsSuccess
	}
	return false
}

type RiderPickedUpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TripId        string                 `protobuf:"bytes,1,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RiderPickedUpRequest) Reset() {
	*x = RiderPickedUpRequest{}
	mi := &file_trip_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RiderPickedUpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiderPickedUpRequest) ProtoMessage() {}

func (x *RiderPickedUpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trip_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiderPickedUpRequest.ProtoReflect.Descriptor instead.
func (*RiderPickedUpRequest) Descriptor() ([]byte, []int) {
	return file_trip_proto_rawDescGZIP(), []int{9}
}

func (x *RiderPickedUpRequest) GetTripId() string {
	if x != nil {
		return x.TripId
	}
	return ""
}

type RiderPickedUpResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	TripId        string                 `protobuf:"bytes,2,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	IsSuccess     bool                   `protobuf:"varint,3,opt,name=is_success,json=isSuccess,proto3" json:"is_success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RiderPickedUpResponse) Reset() {
	*x = RiderPickedUpResponse{}
	mi := &file_trip_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RiderPickedUpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiderPickedUpResponse) ProtoMessage() {}

func (x *RiderPickedUpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trip_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiderPickedUpResponse.ProtoReflect.Descriptor instead.
func (*RiderPickedUpResponse) Descriptor() ([]byte, []int) {
	return file_trip_proto_rawDescGZIP(), []int{10}
}

func (x *RiderPickedUpResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RiderPickedUpResponse) GetTripId() string {
	if x != nil {
		return x.TripId
	}
	return ""
}

func (x *RiderPickedUpResponse) GetIsSuccess() bool {
	if x != nil {
		return x.IsSuccess
	}
	return false
}

type TripCompletedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TripId        string                 `protobuf:"bytes,1,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TripCompletedRequest) Reset() {
	*x = TripCompletedRequest{}
	mi := &file_trip_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TripCompletedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TripCompletedRequest) ProtoMessage() {}

func (x *TripCompletedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trip_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TripCompletedRequest.ProtoReflect.Descriptor instead.
func (*TripCompletedRequest) Descriptor() ([]byte, []int) {
	return file_trip_proto_rawDescGZIP(), []int{11}
}

func (x *TripCompletedRequest) GetTripId() string {
	if x != nil {
		return x.TripId
	}
	return ""
}

type TripCompletedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	TripId        string                 `protobuf:"bytes,2,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	IsSuccess     bool                   `protobuf:"varint,3,opt,name=is_success,json=isSuccess,proto3" json:"is_success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TripCompletedResponse) Reset() {
	*x = TripCompletedResponse{}
	mi := &file_trip_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TripCompletedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TripCompletedResponse) ProtoMessage() {}

func (x *TripCompletedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trip_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TripCompletedResponse.ProtoReflect.Descriptor instead.
func (*TripCompletedResponse) Descriptor() ([]byte, []int) {
	return file_trip_proto_rawDescGZIP(), []int{12}
}

func (x *TripCompletedResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TripCompletedResponse) GetTripId() string {
	if x != nil {
		return x.TripId
	}
	return ""
}

func (x *TripCompletedResponse) GetIsSuccess() bool {
	if x != nil {
		return x.IsSuccess
	}
	return false
}

type GetActiveTripRiderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActiveTripRiderRequest) Reset() {
	*x = GetActiveTripRiderRequest{}
	mi := &file_trip_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActiveTripRiderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActiveTripRiderRequest) ProtoMessage() {}

func (x *GetActiveTripRiderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trip_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActiveTripRiderRequest.ProtoReflect.Descriptor instead.
func (*GetActiveTripRiderRequest) Descriptor() ([]byte, []int) {
	return file_trip_proto_rawDescGZIP(), []int{13}
}

type GetActiveTripRiderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pickup        *GeoLocation           `protobuf:"bytes,1,opt,name=pickup,proto3" json:"pickup,omitempty"`
	Dropoff       *GeoLocation           `protobuf:"bytes,2,opt,name=dropoff,proto3" json:"dropoff,omitempty"`
	RideDetails   *RideDetails           `protobuf:"bytes,3,opt,name=ride_details,json=rideDetails,proto3" json:"ride_details,omitempty"`
	DriverFare    float32                `protobuf:"fixed32,4,opt,name=driver_fare,json=driverFare,proto3" json:"driver_fare,omitempty"`
	RiderId       string                 `protobuf:"bytes,5,opt,name=rider_id,json=riderId,proto3" json:"rider_id,omitempty"`
	TripId        string                 `protobuf:"bytes,6,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActiveTripRiderResponse) Reset() {
	*x = GetActiveTripRiderResponse{}
	mi := &file_trip_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActiveTripRiderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActiveTripRiderResponse) ProtoMessage() {}

func (x *GetActiveTripRiderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trip_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActiveTripRiderResponse.ProtoReflect.Descriptor instead.
func (*GetActiveTripRiderResponse) Descriptor() ([]byte, []int) {
	return file_trip_proto_rawDescGZIP(), []int{14}
}

func (x *GetActiveTripRiderResponse) GetPickup() *GeoLocation {
	if x != nil {
		return x.Pickup
	}
	return nil
}

func (x *GetActiveTripRiderResponse) GetDropoff() *GeoLocation {
	if x != nil {
		return x.Dropoff
	}
	return nil
}

func (x *GetActiveTripRiderResponse) GetRideDetails() *RideDetails {
	if x != nil {
		return x.RideDetails
	}
	return nil
}

func (x *GetActiveTripRiderResponse) GetDriverFare() float32 {
	if x != nil {
		return x.DriverFare
	}
	return 0
}

func (x *GetActiveTripRiderResponse) GetRiderId() string {
	if x != nil {
		return x.RiderId
	}
	return ""
}

func (x *GetActiveTripRiderResponse) GetTripId() string {
	if x != nil {
		return x.TripId
	}
	return ""
}

var File_trip_proto protoreflect.FileDescriptor

const file_trip_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"trip.proto\x12\atrip.v1\"a\n" +
	"\vGeoLocation\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\"Q\n" +
	"\vFareDetails\x12&\n" +
	"\x0famount_in_cents\x18\x01 \x01(\x03R\ramountInCents\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\"M\n" +
	"\x17AcceptTripDriverRequest\x12\x17\n" +
	"\atrip_id\x18\x01 \x01(\tR\x06tripId\x12\x19\n" +
	"\brider_id\x18\x03 \x01(\tR\ariderId\"e\n" +
	"\x18AcceptTripDriverResponse\x12\x17\n" +
	"\atrip_id\x18\x01 \x01(\tR\x06tripId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"w\n" +
	"\vRideDetails\x12)\n" +
	"\x10duration_seconds\x18\x01 \x01(\x03R\x0fdurationSeconds\x12%\n" +
	"\x0edistance_metrs\x18\x02 \x01(\x03R\rdistanceMetrs\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"\x16\n" +
	"\x14GetActiveTripRequest\"\x83\x02\n" +
	"\x15GetActiveTripResponse\x12,\n" +
	"\x06pickup\x18\x01 \x01(\v2\x14.trip.v1.GeoLocationR\x06pickup\x12.\n" +
	"\adropoff\x18\x02 \x01(\v2\x14.trip.v1.GeoLocationR\adropoff\x127\n" +
	"\fride_details\x18\x03 \x01(\v2\x14.trip.v1.RideDetailsR\vrideDetails\x12\x1f\n" +
	"\vdriver_fare\x18\x04 \x01(\x02R\n" +
	"driverFare\x12\x19\n" +
	"\brider_id\x18\x05 \x01(\tR\ariderId\x12\x17\n" +
	"\atrip_id\x18\x06 \x01(\tR\x06tripId\"|\n" +
	"\x11CancelTripRequest\x12\x17\n" +
	"\atrip_id\x18\x01 \x01(\tR\x06tripId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x1b\n" +
	"\tdriver_id\x18\x03 \x01(\tR\bdriverId\x12\x19\n" +
	"\brider_id\x18\x04 \x01(\tR\ariderId\"f\n" +
	"\x12CancelTripResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x17\n" +
	"\atrip_id\x18\x02 \x01(\tR\x06tripId\x12\x1d\n" +
	"\n" +
	"is_success\x18\x03 \x01(\bR\tisSuccess\"/\n" +
	"\x14RiderPickedUpRequest\x12\x17\n" +
	"\atrip_id\x18\x01 \x01(\tR\x06tripId\"i\n" +
	"\x15RiderPickedUpResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x17\n" +
	"\atrip_id\x18\x02 \x01(\tR\x06tripId\x12\x1d\n" +
	"\n" +
	"is_success\x18\x03 \x01(\bR\tisSuccess\"/\n" +
	"\x14TripCompletedRequest\x12\x17\n" +
	"\atrip_id\x18\x01 \x01(\tR\x06tripId\"i\n" +
	"\x15TripCompletedResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x17\n" +
	"\atrip_id\x18\x02 \x01(\tR\x06tripId\x12\x1d\n" +
	"\n" +
	"is_success\x18\x03 \x01(\bR\tisSuccess\"\x1b\n" +
	"\x19GetActiveTripRiderRequest\"\x88\x02\n" +
	"\x1aGetActiveTripRiderResponse\x12,\n" +
	"\x06pickup\x18\x01 \x01(\v2\x14.trip.v1.GeoLocationR\x06pickup\x12.\n" +
	"\adropoff\x18\x02 \x01(\v2\x14.trip.v1.GeoLocationR\adropoff\x127\n" +
	"\fride_details\x18\x03 \x01(\v2\x14.trip.v1.RideDetailsR\vrideDetails\x12\x1f\n" +
	"\vdriver_fare\x18\x04 \x01(\x02R\n" +
	"driverFare\x12\x19\n" +
	"\brider_id\x18\x05 \x01(\tR\ariderId\x12\x17\n" +
	"\atrip_id\x18\x06 \x01(\tR\x06tripId2\xfc\x03\n" +
	"\vTripService\x12W\n" +
	"\x10AcceptTripDriver\x12 .trip.v1.AcceptTripDriverRequest\x1a!.trip.v1.AcceptTripDriverResponse\x12N\n" +
	"\rGetActiveTrip\x12\x1d.trip.v1.GetActiveTripRequest\x1a\x1e.trip.v1.GetActiveTripResponse\x12E\n" +
	"\n" +
	"CancelTrip\x12\x1a.trip.v1.CancelTripRequest\x1a\x1b.trip.v1.CancelTripResponse\x12N\n" +
	"\rRiderPickedUp\x12\x1d.trip.v1.RiderPickedUpRequest\x1a\x1e.trip.v1.RiderPickedUpResponse\x12N\n" +
	"\rTripCompleted\x12\x1d.trip.v1.TripCompletedRequest\x1a\x1e.trip.v1.TripCompletedResponse\x12]\n" +
	"\x12GetActiveTripRider\x12\".trip.v1.GetActiveTripRiderRequest\x1a#.trip.v1.GetActiveTripRiderResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_trip_proto_rawDescOnce sync.Once
	file_trip_proto_rawDescData []byte
)

func file_trip_proto_rawDescGZIP() []byte {
	file_trip_proto_rawDescOnce.Do(func() {
		file_trip_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_trip_proto_rawDesc), len(file_trip_proto_rawDesc)))
	})
	return file_trip_proto_rawDescData
}

var file_trip_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_trip_proto_goTypes = []any{
	(*GeoLocation)(nil),                // 0: trip.v1.GeoLocation
	(*FareDetails)(nil),                // 1: trip.v1.FareDetails
	(*AcceptTripDriverRequest)(nil),    // 2: trip.v1.AcceptTripDriverRequest
	(*AcceptTripDriverResponse)(nil),   // 3: trip.v1.AcceptTripDriverResponse
	(*RideDetails)(nil),                // 4: trip.v1.RideDetails
	(*GetActiveTripRequest)(nil),       // 5: trip.v1.GetActiveTripRequest
	(*GetActiveTripResponse)(nil),      // 6: trip.v1.GetActiveTripResponse
	(*CancelTripRequest)(nil),          // 7: trip.v1.CancelTripRequest
	(*CancelTripResponse)(nil),         // 8: trip.v1.CancelTripResponse
	(*RiderPickedUpRequest)(nil),       // 9: trip.v1.RiderPickedUpRequest
	(*RiderPickedUpResponse)(nil),      // 10: trip.v1.RiderPickedUpResponse
	(*TripCompletedRequest)(nil),       // 11: trip.v1.TripCompletedRequest
	(*TripCompletedResponse)(nil),      // 12: trip.v1.TripCompletedResponse
	(*GetActiveTripRiderRequest)(nil),  // 13: trip.v1.GetActiveTripRiderRequest
	(*GetActiveTripRiderResponse)(nil), // 14: trip.v1.GetActiveTripRiderResponse
}
var file_trip_proto_depIdxs = []int32{
	0,  // 0: trip.v1.GetActiveTripResponse.pickup:type_name -> trip.v1.GeoLocation
	0,  // 1: trip.v1.GetActiveTripResponse.dropoff:type_name -> trip.v1.GeoLocation
	4,  // 2: trip.v1.GetActiveTripResponse.ride_details:type_name -> trip.v1.RideDetails
	0,  // 3: trip.v1.GetActiveTripRiderResponse.pickup:type_name -> trip.v1.GeoLocation
	0,  // 4: trip.v1.GetActiveTripRiderResponse.dropoff:type_name -> trip.v1.GeoLocation
	4,  // 5: trip.v1.GetActiveTripRiderResponse.ride_details:type_name -> trip.v1.RideDetails
	2,  // 6: trip.v1.TripService.AcceptTripDriver:input_type -> trip.v1.AcceptTripDriverRequest
	5,  // 7: trip.v1.TripService.GetActiveTrip:input_type -> trip.v1.GetActiveTripRequest
	7,  // 8: trip.v1.TripService.CancelTrip:input_type -> trip.v1.CancelTripRequest
	9,  // 9: trip.v1.TripService.RiderPickedUp:input_type -> trip.v1.RiderPickedUpRequest
	11, // 10: trip.v1.TripService.TripCompleted:input_type -> trip.v1.TripCompletedRequest
	13, // 11: trip.v1.TripService.GetActiveTripRider:input_type -> trip.v1.GetActiveTripRiderRequest
	3,  // 12: trip.v1.TripService.AcceptTripDriver:output_type -> trip.v1.AcceptTripDriverResponse
	6,  // 13: trip.v1.TripService.GetActiveTrip:output_type -> trip.v1.GetActiveTripResponse
	8,  // 14: trip.v1.TripService.CancelTrip:output_type -> trip.v1.CancelTripResponse
	10, // 15: trip.v1.TripService.RiderPickedUp:output_type -> trip.v1.RiderPickedUpResponse
	12, // 16: trip.v1.TripService.TripCompleted:output_type -> trip.v1.TripCompletedResponse
	14, // 17: trip.v1.TripService.GetActiveTripRider:output_type -> trip.v1.GetActiveTripRiderResponse
	12, // [12:18] is the sub-list for method output_type
	6,  // [6:12] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_trip_proto_init() }
func file_trip_proto_init() {
	if File_trip_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_trip_proto_rawDesc), len(file_trip_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_trip_proto_goTypes,
		DependencyIndexes: file_trip_proto_depIdxs,
		MessageInfos:      file_trip_proto_msgTypes,
	}.Build()
	File_trip_proto = out.File
	file_trip_proto_goTypes = nil
	file_trip_proto_depIdxs = nil
}
