// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: trip.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TripService_AcceptTripDriver_FullMethodName   = "/trip.v1.TripService/AcceptTripDriver"
	TripService_GetActiveTrip_FullMethodName      = "/trip.v1.TripService/GetActiveTrip"
	TripService_CancelTrip_FullMethodName         = "/trip.v1.TripService/CancelTrip"
	TripService_RiderPickedUp_FullMethodName      = "/trip.v1.TripService/RiderPickedUp"
	TripService_TripCompleted_FullMethodName      = "/trip.v1.TripService/TripCompleted"
	TripService_GetActiveTripRider_FullMethodName = "/trip.v1.TripService/GetActiveTripRider"
	TripService_TotalEarningToday_FullMethodName  = "/trip.v1.TripService/TotalEarningToday"
)

// TripServiceClient is the client API for TripService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TripServiceClient interface {
	AcceptTripDriver(ctx context.Context, in *AcceptTripDriverRequest, opts ...grpc.CallOption) (*AcceptTripDriverResponse, error)
	GetActiveTrip(ctx context.Context, in *GetActiveTripRequest, opts ...grpc.CallOption) (*GetActiveTripResponse, error)
	CancelTrip(ctx context.Context, in *CancelTripRequest, opts ...grpc.CallOption) (*CancelTripResponse, error)
	RiderPickedUp(ctx context.Context, in *RiderPickedUpRequest, opts ...grpc.CallOption) (*RiderPickedUpResponse, error)
	TripCompleted(ctx context.Context, in *TripCompletedRequest, opts ...grpc.CallOption) (*TripCompletedResponse, error)
	GetActiveTripRider(ctx context.Context, in *GetActiveTripRiderRequest, opts ...grpc.CallOption) (*GetActiveTripRiderResponse, error)
	TotalEarningToday(ctx context.Context, in *TotalEarningTodayRequest, opts ...grpc.CallOption) (*TotalEarningTodayResponse, error)
}

type tripServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTripServiceClient(cc grpc.ClientConnInterface) TripServiceClient {
	return &tripServiceClient{cc}
}

func (c *tripServiceClient) AcceptTripDriver(ctx context.Context, in *AcceptTripDriverRequest, opts ...grpc.CallOption) (*AcceptTripDriverResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AcceptTripDriverResponse)
	err := c.cc.Invoke(ctx, TripService_AcceptTripDriver_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) GetActiveTrip(ctx context.Context, in *GetActiveTripRequest, opts ...grpc.CallOption) (*GetActiveTripResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetActiveTripResponse)
	err := c.cc.Invoke(ctx, TripService_GetActiveTrip_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) CancelTrip(ctx context.Context, in *CancelTripRequest, opts ...grpc.CallOption) (*CancelTripResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelTripResponse)
	err := c.cc.Invoke(ctx, TripService_CancelTrip_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) RiderPickedUp(ctx context.Context, in *RiderPickedUpRequest, opts ...grpc.CallOption) (*RiderPickedUpResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RiderPickedUpResponse)
	err := c.cc.Invoke(ctx, TripService_RiderPickedUp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) TripCompleted(ctx context.Context, in *TripCompletedRequest, opts ...grpc.CallOption) (*TripCompletedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TripCompletedResponse)
	err := c.cc.Invoke(ctx, TripService_TripCompleted_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) GetActiveTripRider(ctx context.Context, in *GetActiveTripRiderRequest, opts ...grpc.CallOption) (*GetActiveTripRiderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetActiveTripRiderResponse)
	err := c.cc.Invoke(ctx, TripService_GetActiveTripRider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) TotalEarningToday(ctx context.Context, in *TotalEarningTodayRequest, opts ...grpc.CallOption) (*TotalEarningTodayResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TotalEarningTodayResponse)
	err := c.cc.Invoke(ctx, TripService_TotalEarningToday_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TripServiceServer is the server API for TripService service.
// All implementations must embed UnimplementedTripServiceServer
// for forward compatibility.
type TripServiceServer interface {
	AcceptTripDriver(context.Context, *AcceptTripDriverRequest) (*AcceptTripDriverResponse, error)
	GetActiveTrip(context.Context, *GetActiveTripRequest) (*GetActiveTripResponse, error)
	CancelTrip(context.Context, *CancelTripRequest) (*CancelTripResponse, error)
	RiderPickedUp(context.Context, *RiderPickedUpRequest) (*RiderPickedUpResponse, error)
	TripCompleted(context.Context, *TripCompletedRequest) (*TripCompletedResponse, error)
	GetActiveTripRider(context.Context, *GetActiveTripRiderRequest) (*GetActiveTripRiderResponse, error)
	TotalEarningToday(context.Context, *TotalEarningTodayRequest) (*TotalEarningTodayResponse, error)
	mustEmbedUnimplementedTripServiceServer()
}

// UnimplementedTripServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTripServiceServer struct{}

func (UnimplementedTripServiceServer) AcceptTripDriver(context.Context, *AcceptTripDriverRequest) (*AcceptTripDriverResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AcceptTripDriver not implemented")
}
func (UnimplementedTripServiceServer) GetActiveTrip(context.Context, *GetActiveTripRequest) (*GetActiveTripResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetActiveTrip not implemented")
}
func (UnimplementedTripServiceServer) CancelTrip(context.Context, *CancelTripRequest) (*CancelTripResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelTrip not implemented")
}
func (UnimplementedTripServiceServer) RiderPickedUp(context.Context, *RiderPickedUpRequest) (*RiderPickedUpResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RiderPickedUp not implemented")
}
func (UnimplementedTripServiceServer) TripCompleted(context.Context, *TripCompletedRequest) (*TripCompletedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TripCompleted not implemented")
}
func (UnimplementedTripServiceServer) GetActiveTripRider(context.Context, *GetActiveTripRiderRequest) (*GetActiveTripRiderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetActiveTripRider not implemented")
}
func (UnimplementedTripServiceServer) TotalEarningToday(context.Context, *TotalEarningTodayRequest) (*TotalEarningTodayResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TotalEarningToday not implemented")
}
func (UnimplementedTripServiceServer) mustEmbedUnimplementedTripServiceServer() {}
func (UnimplementedTripServiceServer) testEmbeddedByValue()                     {}

// UnsafeTripServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TripServiceServer will
// result in compilation errors.
type UnsafeTripServiceServer interface {
	mustEmbedUnimplementedTripServiceServer()
}

func RegisterTripServiceServer(s grpc.ServiceRegistrar, srv TripServiceServer) {
	// If the following call panics, it indicates UnimplementedTripServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TripService_ServiceDesc, srv)
}

func _TripService_AcceptTripDriver_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcceptTripDriverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).AcceptTripDriver(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_AcceptTripDriver_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).AcceptTripDriver(ctx, req.(*AcceptTripDriverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_GetActiveTrip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetActiveTripRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).GetActiveTrip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_GetActiveTrip_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).GetActiveTrip(ctx, req.(*GetActiveTripRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_CancelTrip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelTripRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).CancelTrip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_CancelTrip_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).CancelTrip(ctx, req.(*CancelTripRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_RiderPickedUp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RiderPickedUpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).RiderPickedUp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_RiderPickedUp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).RiderPickedUp(ctx, req.(*RiderPickedUpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_TripCompleted_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TripCompletedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).TripCompleted(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_TripCompleted_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).TripCompleted(ctx, req.(*TripCompletedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_GetActiveTripRider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetActiveTripRiderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).GetActiveTripRider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_GetActiveTripRider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).GetActiveTripRider(ctx, req.(*GetActiveTripRiderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_TotalEarningToday_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TotalEarningTodayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).TotalEarningToday(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TripService_TotalEarningToday_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).TotalEarningToday(ctx, req.(*TotalEarningTodayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TripService_ServiceDesc is the grpc.ServiceDesc for TripService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TripService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "trip.v1.TripService",
	HandlerType: (*TripServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AcceptTripDriver",
			Handler:    _TripService_AcceptTripDriver_Handler,
		},
		{
			MethodName: "GetActiveTrip",
			Handler:    _TripService_GetActiveTrip_Handler,
		},
		{
			MethodName: "CancelTrip",
			Handler:    _TripService_CancelTrip_Handler,
		},
		{
			MethodName: "RiderPickedUp",
			Handler:    _TripService_RiderPickedUp_Handler,
		},
		{
			MethodName: "TripCompleted",
			Handler:    _TripService_TripCompleted_Handler,
		},
		{
			MethodName: "GetActiveTripRider",
			Handler:    _TripService_GetActiveTripRider_Handler,
		},
		{
			MethodName: "TotalEarningToday",
			Handler:    _TripService_TotalEarningToday_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "trip.proto",
}
