// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: auth.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RiderLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RiderLoginRequest) Reset() {
	*x = RiderLoginRequest{}
	mi := &file_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RiderLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiderLoginRequest) ProtoMessage() {}

func (x *RiderLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiderLoginRequest.ProtoReflect.Descriptor instead.
func (*RiderLoginRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{0}
}

func (x *RiderLoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RiderLoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RiderAuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	StatusCode    int32                  `protobuf:"varint,4,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RiderAuthResponse) Reset() {
	*x = RiderAuthResponse{}
	mi := &file_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RiderAuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiderAuthResponse) ProtoMessage() {}

func (x *RiderAuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiderAuthResponse.ProtoReflect.Descriptor instead.
func (*RiderAuthResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{1}
}

func (x *RiderAuthResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *RiderAuthResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *RiderAuthResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RiderAuthResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *RiderAuthResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RiderRegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Firstname     string                 `protobuf:"bytes,1,opt,name=firstname,proto3" json:"firstname,omitempty"`
	Lastname      string                 `protobuf:"bytes,2,opt,name=lastname,proto3" json:"lastname,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,5,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,6,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	HomeAddress   string                 `protobuf:"bytes,7,opt,name=home_address,json=homeAddress,proto3" json:"home_address,omitempty"`
	WorkAddress   string                 `protobuf:"bytes,8,opt,name=work_address,json=workAddress,proto3" json:"work_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RiderRegisterRequest) Reset() {
	*x = RiderRegisterRequest{}
	mi := &file_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RiderRegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiderRegisterRequest) ProtoMessage() {}

func (x *RiderRegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiderRegisterRequest.ProtoReflect.Descriptor instead.
func (*RiderRegisterRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{2}
}

func (x *RiderRegisterRequest) GetFirstname() string {
	if x != nil {
		return x.Firstname
	}
	return ""
}

func (x *RiderRegisterRequest) GetLastname() string {
	if x != nil {
		return x.Lastname
	}
	return ""
}

func (x *RiderRegisterRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RiderRegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RiderRegisterRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *RiderRegisterRequest) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *RiderRegisterRequest) GetHomeAddress() string {
	if x != nil {
		return x.HomeAddress
	}
	return ""
}

func (x *RiderRegisterRequest) GetWorkAddress() string {
	if x != nil {
		return x.WorkAddress
	}
	return ""
}

type GetRiderInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRiderInfoRequest) Reset() {
	*x = GetRiderInfoRequest{}
	mi := &file_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRiderInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRiderInfoRequest) ProtoMessage() {}

func (x *GetRiderInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRiderInfoRequest.ProtoReflect.Descriptor instead.
func (*GetRiderInfoRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{3}
}

type GetRiderInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Firstname     string                 `protobuf:"bytes,1,opt,name=firstname,proto3" json:"firstname,omitempty"`
	Lastname      string                 `protobuf:"bytes,2,opt,name=lastname,proto3" json:"lastname,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,4,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,5,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Rating        float64                `protobuf:"fixed64,6,opt,name=rating,proto3" json:"rating,omitempty"`
	Success       bool                   `protobuf:"varint,7,opt,name=success,proto3" json:"success,omitempty"`
	StatusCode    int32                  `protobuf:"varint,8,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message       string                 `protobuf:"bytes,9,opt,name=message,proto3" json:"message,omitempty"`
	RiderId       string                 `protobuf:"bytes,10,opt,name=rider_id,json=riderId,proto3" json:"rider_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRiderInfoResponse) Reset() {
	*x = GetRiderInfoResponse{}
	mi := &file_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRiderInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRiderInfoResponse) ProtoMessage() {}

func (x *GetRiderInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRiderInfoResponse.ProtoReflect.Descriptor instead.
func (*GetRiderInfoResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{4}
}

func (x *GetRiderInfoResponse) GetFirstname() string {
	if x != nil {
		return x.Firstname
	}
	return ""
}

func (x *GetRiderInfoResponse) GetLastname() string {
	if x != nil {
		return x.Lastname
	}
	return ""
}

func (x *GetRiderInfoResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *GetRiderInfoResponse) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *GetRiderInfoResponse) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *GetRiderInfoResponse) GetRating() float64 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *GetRiderInfoResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetRiderInfoResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *GetRiderInfoResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetRiderInfoResponse) GetRiderId() string {
	if x != nil {
		return x.RiderId
	}
	return ""
}

type LogoutRiderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRiderRequest) Reset() {
	*x = LogoutRiderRequest{}
	mi := &file_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRiderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRiderRequest) ProtoMessage() {}

func (x *LogoutRiderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRiderRequest.ProtoReflect.Descriptor instead.
func (*LogoutRiderRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{5}
}

type LogoutRiderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	StatusCode    int32                  `protobuf:"varint,4,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRiderResponse) Reset() {
	*x = LogoutRiderResponse{}
	mi := &file_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRiderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRiderResponse) ProtoMessage() {}

func (x *LogoutRiderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRiderResponse.ProtoReflect.Descriptor instead.
func (*LogoutRiderResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{6}
}

func (x *LogoutRiderResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LogoutRiderResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *LogoutRiderResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LogoutRiderResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *LogoutRiderResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DriverInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Firstname     string                 `protobuf:"bytes,1,opt,name=firstname,proto3" json:"firstname,omitempty"`
	Lastname      string                 `protobuf:"bytes,2,opt,name=lastname,proto3" json:"lastname,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,5,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	LicenseNo     string                 `protobuf:"bytes,6,opt,name=license_no,json=licenseNo,proto3" json:"license_no,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,7,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverInfo) Reset() {
	*x = DriverInfo{}
	mi := &file_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverInfo) ProtoMessage() {}

func (x *DriverInfo) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverInfo.ProtoReflect.Descriptor instead.
func (*DriverInfo) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{7}
}

func (x *DriverInfo) GetFirstname() string {
	if x != nil {
		return x.Firstname
	}
	return ""
}

func (x *DriverInfo) GetLastname() string {
	if x != nil {
		return x.Lastname
	}
	return ""
}

func (x *DriverInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *DriverInfo) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *DriverInfo) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *DriverInfo) GetLicenseNo() string {
	if x != nil {
		return x.LicenseNo
	}
	return ""
}

func (x *DriverInfo) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

type VehicleInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Carname           string                 `protobuf:"bytes,1,opt,name=carname,proto3" json:"carname,omitempty"`
	Brand             string                 `protobuf:"bytes,2,opt,name=brand,proto3" json:"brand,omitempty"`
	Model             string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	Make              string                 `protobuf:"bytes,4,opt,name=make,proto3" json:"make,omitempty"`
	Year              int32                  `protobuf:"varint,5,opt,name=year,proto3" json:"year,omitempty"`
	Color             string                 `protobuf:"bytes,6,opt,name=color,proto3" json:"color,omitempty"`
	CarPlate          string                 `protobuf:"bytes,7,opt,name=car_plate,json=carPlate,proto3" json:"car_plate,omitempty"`
	InsurancePolicyNo string                 `protobuf:"bytes,8,opt,name=insurance_policy_no,json=insurancePolicyNo,proto3" json:"insurance_policy_no,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *VehicleInfo) Reset() {
	*x = VehicleInfo{}
	mi := &file_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VehicleInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VehicleInfo) ProtoMessage() {}

func (x *VehicleInfo) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VehicleInfo.ProtoReflect.Descriptor instead.
func (*VehicleInfo) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{8}
}

func (x *VehicleInfo) GetCarname() string {
	if x != nil {
		return x.Carname
	}
	return ""
}

func (x *VehicleInfo) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *VehicleInfo) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *VehicleInfo) GetMake() string {
	if x != nil {
		return x.Make
	}
	return ""
}

func (x *VehicleInfo) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *VehicleInfo) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *VehicleInfo) GetCarPlate() string {
	if x != nil {
		return x.CarPlate
	}
	return ""
}

func (x *VehicleInfo) GetInsurancePolicyNo() string {
	if x != nil {
		return x.InsurancePolicyNo
	}
	return ""
}

type DriverRegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverInfo    *DriverInfo            `protobuf:"bytes,1,opt,name=driver_info,json=driverInfo,proto3" json:"driver_info,omitempty"`
	CarInfo       *VehicleInfo           `protobuf:"bytes,2,opt,name=car_info,json=carInfo,proto3" json:"car_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverRegisterRequest) Reset() {
	*x = DriverRegisterRequest{}
	mi := &file_auth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverRegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverRegisterRequest) ProtoMessage() {}

func (x *DriverRegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverRegisterRequest.ProtoReflect.Descriptor instead.
func (*DriverRegisterRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{9}
}

func (x *DriverRegisterRequest) GetDriverInfo() *DriverInfo {
	if x != nil {
		return x.DriverInfo
	}
	return nil
}

func (x *DriverRegisterRequest) GetCarInfo() *VehicleInfo {
	if x != nil {
		return x.CarInfo
	}
	return nil
}

type DriverAuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	StatusCode    int32                  `protobuf:"varint,4,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverAuthResponse) Reset() {
	*x = DriverAuthResponse{}
	mi := &file_auth_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverAuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverAuthResponse) ProtoMessage() {}

func (x *DriverAuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverAuthResponse.ProtoReflect.Descriptor instead.
func (*DriverAuthResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{10}
}

func (x *DriverAuthResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *DriverAuthResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *DriverAuthResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DriverAuthResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *DriverAuthResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DriverLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverLoginRequest) Reset() {
	*x = DriverLoginRequest{}
	mi := &file_auth_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverLoginRequest) ProtoMessage() {}

func (x *DriverLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverLoginRequest.ProtoReflect.Descriptor instead.
func (*DriverLoginRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{11}
}

func (x *DriverLoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *DriverLoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type GetDriverInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDriverInfoRequest) Reset() {
	*x = GetDriverInfoRequest{}
	mi := &file_auth_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDriverInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDriverInfoRequest) ProtoMessage() {}

func (x *GetDriverInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDriverInfoRequest.ProtoReflect.Descriptor instead.
func (*GetDriverInfoRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{12}
}

type GetDriverInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Firstname     string                 `protobuf:"bytes,1,opt,name=firstname,proto3" json:"firstname,omitempty"`
	Lastname      string                 `protobuf:"bytes,2,opt,name=lastname,proto3" json:"lastname,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,5,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	LicenseNo     string                 `protobuf:"bytes,6,opt,name=license_no,json=licenseNo,proto3" json:"license_no,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,7,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Rating        float64                `protobuf:"fixed64,8,opt,name=rating,proto3" json:"rating,omitempty"`
	Success       bool                   `protobuf:"varint,9,opt,name=success,proto3" json:"success,omitempty"`
	StatusCode    int32                  `protobuf:"varint,10,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message       string                 `protobuf:"bytes,11,opt,name=message,proto3" json:"message,omitempty"`
	DriverId      string                 `protobuf:"bytes,12,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDriverInfoResponse) Reset() {
	*x = GetDriverInfoResponse{}
	mi := &file_auth_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDriverInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDriverInfoResponse) ProtoMessage() {}

func (x *GetDriverInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDriverInfoResponse.ProtoReflect.Descriptor instead.
func (*GetDriverInfoResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{13}
}

func (x *GetDriverInfoResponse) GetFirstname() string {
	if x != nil {
		return x.Firstname
	}
	return ""
}

func (x *GetDriverInfoResponse) GetLastname() string {
	if x != nil {
		return x.Lastname
	}
	return ""
}

func (x *GetDriverInfoResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *GetDriverInfoResponse) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *GetDriverInfoResponse) GetLicenseNo() string {
	if x != nil {
		return x.LicenseNo
	}
	return ""
}

func (x *GetDriverInfoResponse) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *GetDriverInfoResponse) GetRating() float64 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *GetDriverInfoResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetDriverInfoResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *GetDriverInfoResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetDriverInfoResponse) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

type LogoutDriverRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutDriverRequest) Reset() {
	*x = LogoutDriverRequest{}
	mi := &file_auth_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutDriverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutDriverRequest) ProtoMessage() {}

func (x *LogoutDriverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutDriverRequest.ProtoReflect.Descriptor instead.
func (*LogoutDriverRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{14}
}

type LogoutDriverResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	StatusCode    int32                  `protobuf:"varint,4,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutDriverResponse) Reset() {
	*x = LogoutDriverResponse{}
	mi := &file_auth_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutDriverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutDriverResponse) ProtoMessage() {}

func (x *LogoutDriverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutDriverResponse.ProtoReflect.Descriptor instead.
func (*LogoutDriverResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{15}
}

func (x *LogoutDriverResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LogoutDriverResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *LogoutDriverResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LogoutDriverResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *LogoutDriverResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetDriverCarInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDriverCarInfoRequest) Reset() {
	*x = GetDriverCarInfoRequest{}
	mi := &file_auth_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDriverCarInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDriverCarInfoRequest) ProtoMessage() {}

func (x *GetDriverCarInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDriverCarInfoRequest.ProtoReflect.Descriptor instead.
func (*GetDriverCarInfoRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{16}
}

type GetDriverCarInfoResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	VehicleId         string                 `protobuf:"bytes,1,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`
	Carname           string                 `protobuf:"bytes,2,opt,name=carname,proto3" json:"carname,omitempty"`
	Brand             string                 `protobuf:"bytes,3,opt,name=brand,proto3" json:"brand,omitempty"`
	Model             string                 `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	Make              string                 `protobuf:"bytes,5,opt,name=make,proto3" json:"make,omitempty"`
	Year              int32                  `protobuf:"varint,6,opt,name=year,proto3" json:"year,omitempty"`
	Coloe             string                 `protobuf:"bytes,7,opt,name=coloe,proto3" json:"coloe,omitempty"`
	CarPlate          string                 `protobuf:"bytes,8,opt,name=car_plate,json=carPlate,proto3" json:"car_plate,omitempty"`
	InsurancePolicyNo string                 `protobuf:"bytes,9,opt,name=insurance_policy_no,json=insurancePolicyNo,proto3" json:"insurance_policy_no,omitempty"`
	IsVerified        bool                   `protobuf:"varint,10,opt,name=is_verified,json=isVerified,proto3" json:"is_verified,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetDriverCarInfoResponse) Reset() {
	*x = GetDriverCarInfoResponse{}
	mi := &file_auth_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDriverCarInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDriverCarInfoResponse) ProtoMessage() {}

func (x *GetDriverCarInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDriverCarInfoResponse.ProtoReflect.Descriptor instead.
func (*GetDriverCarInfoResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{17}
}

func (x *GetDriverCarInfoResponse) GetVehicleId() string {
	if x != nil {
		return x.VehicleId
	}
	return ""
}

func (x *GetDriverCarInfoResponse) GetCarname() string {
	if x != nil {
		return x.Carname
	}
	return ""
}

func (x *GetDriverCarInfoResponse) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *GetDriverCarInfoResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *GetDriverCarInfoResponse) GetMake() string {
	if x != nil {
		return x.Make
	}
	return ""
}

func (x *GetDriverCarInfoResponse) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *GetDriverCarInfoResponse) GetColoe() string {
	if x != nil {
		return x.Coloe
	}
	return ""
}

func (x *GetDriverCarInfoResponse) GetCarPlate() string {
	if x != nil {
		return x.CarPlate
	}
	return ""
}

func (x *GetDriverCarInfoResponse) GetInsurancePolicyNo() string {
	if x != nil {
		return x.InsurancePolicyNo
	}
	return ""
}

func (x *GetDriverCarInfoResponse) GetIsVerified() bool {
	if x != nil {
		return x.IsVerified
	}
	return false
}

// ///////////////////////////////////
// ///////////////////////////////////
// ///////////////////////////////////
// ///////////////////////////////////
// ///////////////////////////////////
type CheckHealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckHealthRequest) Reset() {
	*x = CheckHealthRequest{}
	mi := &file_auth_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckHealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckHealthRequest) ProtoMessage() {}

func (x *CheckHealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckHealthRequest.ProtoReflect.Descriptor instead.
func (*CheckHealthRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{18}
}

func (x *CheckHealthRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

type CheckHealthRespone struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	StatusCode    int32                  `protobuf:"varint,4,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckHealthRespone) Reset() {
	*x = CheckHealthRespone{}
	mi := &file_auth_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckHealthRespone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckHealthRespone) ProtoMessage() {}

func (x *CheckHealthRespone) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckHealthRespone.ProtoReflect.Descriptor instead.
func (*CheckHealthRespone) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{19}
}

func (x *CheckHealthRespone) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CheckHealthRespone) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *CheckHealthRespone) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_auth_proto protoreflect.FileDescriptor

const file_auth_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"auth.proto\x12\x04auth\"E\n" +
	"\x11RiderLoginRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\xb0\x01\n" +
	"\x11RiderAuthResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x1f\n" +
	"\vstatus_code\x18\x04 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\"\x88\x02\n" +
	"\x14RiderRegisterRequest\x12\x1c\n" +
	"\tfirstname\x18\x01 \x01(\tR\tfirstname\x12\x1a\n" +
	"\blastname\x18\x02 \x01(\tR\blastname\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12!\n" +
	"\fphone_number\x18\x05 \x01(\tR\vphoneNumber\x12\x1b\n" +
	"\timage_url\x18\x06 \x01(\tR\bimageUrl\x12!\n" +
	"\fhome_address\x18\a \x01(\tR\vhomeAddress\x12!\n" +
	"\fwork_address\x18\b \x01(\tR\vworkAddress\"\x15\n" +
	"\x13GetRiderInfoRequest\"\xae\x02\n" +
	"\x14GetRiderInfoResponse\x12\x1c\n" +
	"\tfirstname\x18\x01 \x01(\tR\tfirstname\x12\x1a\n" +
	"\blastname\x18\x02 \x01(\tR\blastname\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12!\n" +
	"\fphone_number\x18\x04 \x01(\tR\vphoneNumber\x12\x1b\n" +
	"\timage_url\x18\x05 \x01(\tR\bimageUrl\x12\x16\n" +
	"\x06rating\x18\x06 \x01(\x01R\x06rating\x12\x18\n" +
	"\asuccess\x18\a \x01(\bR\asuccess\x12\x1f\n" +
	"\vstatus_code\x18\b \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\t \x01(\tR\amessage\x12\x19\n" +
	"\brider_id\x18\n" +
	" \x01(\tR\ariderId\"\x14\n" +
	"\x12LogoutRiderRequest\"\xb2\x01\n" +
	"\x13LogoutRiderResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x1f\n" +
	"\vstatus_code\x18\x04 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\"\xd7\x01\n" +
	"\n" +
	"DriverInfo\x12\x1c\n" +
	"\tfirstname\x18\x01 \x01(\tR\tfirstname\x12\x1a\n" +
	"\blastname\x18\x02 \x01(\tR\blastname\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12!\n" +
	"\fphone_number\x18\x05 \x01(\tR\vphoneNumber\x12\x1d\n" +
	"\n" +
	"license_no\x18\x06 \x01(\tR\tlicenseNo\x12\x1b\n" +
	"\timage_url\x18\a \x01(\tR\bimageUrl\"\xde\x01\n" +
	"\vVehicleInfo\x12\x18\n" +
	"\acarname\x18\x01 \x01(\tR\acarname\x12\x14\n" +
	"\x05brand\x18\x02 \x01(\tR\x05brand\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12\x12\n" +
	"\x04make\x18\x04 \x01(\tR\x04make\x12\x12\n" +
	"\x04year\x18\x05 \x01(\x05R\x04year\x12\x14\n" +
	"\x05color\x18\x06 \x01(\tR\x05color\x12\x1b\n" +
	"\tcar_plate\x18\a \x01(\tR\bcarPlate\x12.\n" +
	"\x13insurance_policy_no\x18\b \x01(\tR\x11insurancePolicyNo\"x\n" +
	"\x15DriverRegisterRequest\x121\n" +
	"\vdriver_info\x18\x01 \x01(\v2\x10.auth.DriverInfoR\n" +
	"driverInfo\x12,\n" +
	"\bcar_info\x18\x02 \x01(\v2\x11.auth.VehicleInfoR\acarInfo\"\xb1\x01\n" +
	"\x12DriverAuthResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x1f\n" +
	"\vstatus_code\x18\x04 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\"F\n" +
	"\x12DriverLoginRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\x16\n" +
	"\x14GetDriverInfoRequest\"\xd0\x02\n" +
	"\x15GetDriverInfoResponse\x12\x1c\n" +
	"\tfirstname\x18\x01 \x01(\tR\tfirstname\x12\x1a\n" +
	"\blastname\x18\x02 \x01(\tR\blastname\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12!\n" +
	"\fphone_number\x18\x05 \x01(\tR\vphoneNumber\x12\x1d\n" +
	"\n" +
	"license_no\x18\x06 \x01(\tR\tlicenseNo\x12\x1b\n" +
	"\timage_url\x18\a \x01(\tR\bimageUrl\x12\x16\n" +
	"\x06rating\x18\b \x01(\x01R\x06rating\x12\x18\n" +
	"\asuccess\x18\t \x01(\bR\asuccess\x12\x1f\n" +
	"\vstatus_code\x18\n" +
	" \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\v \x01(\tR\amessage\x12\x1b\n" +
	"\tdriver_id\x18\f \x01(\tR\bdriverId\"\x15\n" +
	"\x13LogoutDriverRequest\"\xb3\x01\n" +
	"\x14LogoutDriverResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x1f\n" +
	"\vstatus_code\x18\x04 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\"\x19\n" +
	"\x17GetDriverCarInfoRequest\"\xab\x02\n" +
	"\x18GetDriverCarInfoResponse\x12\x1d\n" +
	"\n" +
	"vehicle_id\x18\x01 \x01(\tR\tvehicleId\x12\x18\n" +
	"\acarname\x18\x02 \x01(\tR\acarname\x12\x14\n" +
	"\x05brand\x18\x03 \x01(\tR\x05brand\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\x12\x12\n" +
	"\x04make\x18\x05 \x01(\tR\x04make\x12\x12\n" +
	"\x04year\x18\x06 \x01(\x05R\x04year\x12\x14\n" +
	"\x05coloe\x18\a \x01(\tR\x05coloe\x12\x1b\n" +
	"\tcar_plate\x18\b \x01(\tR\bcarPlate\x12.\n" +
	"\x13insurance_policy_no\x18\t \x01(\tR\x11insurancePolicyNo\x12\x1f\n" +
	"\vis_verified\x18\n" +
	" \x01(\bR\n" +
	"isVerified\"7\n" +
	"\x12CheckHealthRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\"i\n" +
	"\x12CheckHealthRespone\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x1f\n" +
	"\vstatus_code\x18\x04 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage2\xa3\x02\n" +
	"\x10RiderAuthService\x12D\n" +
	"\rRegisterRider\x12\x1a.auth.RiderRegisterRequest\x1a\x17.auth.RiderAuthResponse\x12>\n" +
	"\n" +
	"LoginRider\x12\x17.auth.RiderLoginRequest\x1a\x17.auth.RiderAuthResponse\x12E\n" +
	"\fGetRiderInfo\x12\x19.auth.GetRiderInfoRequest\x1a\x1a.auth.GetRiderInfoResponse\x12B\n" +
	"\vLogoutRider\x12\x18.auth.LogoutRiderRequest\x1a\x19.auth.LogoutRiderResponse2\x83\x03\n" +
	"\x11DriverAuthService\x12A\n" +
	"\vLoginDriver\x12\x18.auth.DriverLoginRequest\x1a\x18.auth.DriverAuthResponse\x12G\n" +
	"\x0eRegisterDriver\x12\x1b.auth.DriverRegisterRequest\x1a\x18.auth.DriverAuthResponse\x12H\n" +
	"\rGetDriverInfo\x12\x1a.auth.GetDriverInfoRequest\x1a\x1b.auth.GetDriverInfoResponse\x12Q\n" +
	"\x10GetDriverCarInfo\x12\x1d.auth.GetDriverCarInfoRequest\x1a\x1e.auth.GetDriverCarInfoResponse\x12E\n" +
	"\fLogoutDriver\x12\x19.auth.LogoutDriverRequest\x1a\x1a.auth.LogoutDriverResponse2W\n" +
	"\x12HealthCheckService\x12A\n" +
	"\vCheckHealth\x12\x18.auth.CheckHealthRequest\x1a\x18.auth.CheckHealthResponeB\x06Z\x04./pbb\x06proto3"

var (
	file_auth_proto_rawDescOnce sync.Once
	file_auth_proto_rawDescData []byte
)

func file_auth_proto_rawDescGZIP() []byte {
	file_auth_proto_rawDescOnce.Do(func() {
		file_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_proto_rawDesc), len(file_auth_proto_rawDesc)))
	})
	return file_auth_proto_rawDescData
}

var file_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_auth_proto_goTypes = []any{
	(*RiderLoginRequest)(nil),        // 0: auth.RiderLoginRequest
	(*RiderAuthResponse)(nil),        // 1: auth.RiderAuthResponse
	(*RiderRegisterRequest)(nil),     // 2: auth.RiderRegisterRequest
	(*GetRiderInfoRequest)(nil),      // 3: auth.GetRiderInfoRequest
	(*GetRiderInfoResponse)(nil),     // 4: auth.GetRiderInfoResponse
	(*LogoutRiderRequest)(nil),       // 5: auth.LogoutRiderRequest
	(*LogoutRiderResponse)(nil),      // 6: auth.LogoutRiderResponse
	(*DriverInfo)(nil),               // 7: auth.DriverInfo
	(*VehicleInfo)(nil),              // 8: auth.VehicleInfo
	(*DriverRegisterRequest)(nil),    // 9: auth.DriverRegisterRequest
	(*DriverAuthResponse)(nil),       // 10: auth.DriverAuthResponse
	(*DriverLoginRequest)(nil),       // 11: auth.DriverLoginRequest
	(*GetDriverInfoRequest)(nil),     // 12: auth.GetDriverInfoRequest
	(*GetDriverInfoResponse)(nil),    // 13: auth.GetDriverInfoResponse
	(*LogoutDriverRequest)(nil),      // 14: auth.LogoutDriverRequest
	(*LogoutDriverResponse)(nil),     // 15: auth.LogoutDriverResponse
	(*GetDriverCarInfoRequest)(nil),  // 16: auth.GetDriverCarInfoRequest
	(*GetDriverCarInfoResponse)(nil), // 17: auth.GetDriverCarInfoResponse
	(*CheckHealthRequest)(nil),       // 18: auth.CheckHealthRequest
	(*CheckHealthRespone)(nil),       // 19: auth.CheckHealthRespone
}
var file_auth_proto_depIdxs = []int32{
	7,  // 0: auth.DriverRegisterRequest.driver_info:type_name -> auth.DriverInfo
	8,  // 1: auth.DriverRegisterRequest.car_info:type_name -> auth.VehicleInfo
	2,  // 2: auth.RiderAuthService.RegisterRider:input_type -> auth.RiderRegisterRequest
	0,  // 3: auth.RiderAuthService.LoginRider:input_type -> auth.RiderLoginRequest
	3,  // 4: auth.RiderAuthService.GetRiderInfo:input_type -> auth.GetRiderInfoRequest
	5,  // 5: auth.RiderAuthService.LogoutRider:input_type -> auth.LogoutRiderRequest
	11, // 6: auth.DriverAuthService.LoginDriver:input_type -> auth.DriverLoginRequest
	9,  // 7: auth.DriverAuthService.RegisterDriver:input_type -> auth.DriverRegisterRequest
	12, // 8: auth.DriverAuthService.GetDriverInfo:input_type -> auth.GetDriverInfoRequest
	16, // 9: auth.DriverAuthService.GetDriverCarInfo:input_type -> auth.GetDriverCarInfoRequest
	14, // 10: auth.DriverAuthService.LogoutDriver:input_type -> auth.LogoutDriverRequest
	18, // 11: auth.HealthCheckService.CheckHealth:input_type -> auth.CheckHealthRequest
	1,  // 12: auth.RiderAuthService.RegisterRider:output_type -> auth.RiderAuthResponse
	1,  // 13: auth.RiderAuthService.LoginRider:output_type -> auth.RiderAuthResponse
	4,  // 14: auth.RiderAuthService.GetRiderInfo:output_type -> auth.GetRiderInfoResponse
	6,  // 15: auth.RiderAuthService.LogoutRider:output_type -> auth.LogoutRiderResponse
	10, // 16: auth.DriverAuthService.LoginDriver:output_type -> auth.DriverAuthResponse
	10, // 17: auth.DriverAuthService.RegisterDriver:output_type -> auth.DriverAuthResponse
	13, // 18: auth.DriverAuthService.GetDriverInfo:output_type -> auth.GetDriverInfoResponse
	17, // 19: auth.DriverAuthService.GetDriverCarInfo:output_type -> auth.GetDriverCarInfoResponse
	15, // 20: auth.DriverAuthService.LogoutDriver:output_type -> auth.LogoutDriverResponse
	19, // 21: auth.HealthCheckService.CheckHealth:output_type -> auth.CheckHealthRespone
	12, // [12:22] is the sub-list for method output_type
	2,  // [2:12] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_auth_proto_init() }
func file_auth_proto_init() {
	if File_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_proto_rawDesc), len(file_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_auth_proto_goTypes,
		DependencyIndexes: file_auth_proto_depIdxs,
		MessageInfos:      file_auth_proto_msgTypes,
	}.Build()
	File_auth_proto = out.File
	file_auth_proto_goTypes = nil
	file_auth_proto_depIdxs = nil
}
