// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: auth.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RiderAuthService_RegisterRider_FullMethodName       = "/auth.RiderAuthService/RegisterRider"
	RiderAuthService_LoginRider_FullMethodName          = "/auth.RiderAuthService/LoginRider"
	RiderAuthService_GetRiderInfo_FullMethodName        = "/auth.RiderAuthService/GetRiderInfo"
	RiderAuthService_LogoutRider_FullMethodName         = "/auth.RiderAuthService/LogoutRider"
	RiderAuthService_UpdatePasswordRider_FullMethodName = "/auth.RiderAuthService/UpdatePasswordRider"
)

// RiderAuthServiceClient is the client API for RiderAuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RiderAuthServiceClient interface {
	RegisterRider(ctx context.Context, in *RiderRegisterRequest, opts ...grpc.CallOption) (*RiderAuthResponse, error)
	LoginRider(ctx context.Context, in *RiderLoginRequest, opts ...grpc.CallOption) (*RiderAuthResponse, error)
	GetRiderInfo(ctx context.Context, in *GetRiderInfoRequest, opts ...grpc.CallOption) (*GetRiderInfoResponse, error)
	LogoutRider(ctx context.Context, in *LogoutRiderRequest, opts ...grpc.CallOption) (*LogoutRiderResponse, error)
	UpdatePasswordRider(ctx context.Context, in *UpdatePasswordRiderRequest, opts ...grpc.CallOption) (*UpdatePasswordRiderResponse, error)
}

type riderAuthServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRiderAuthServiceClient(cc grpc.ClientConnInterface) RiderAuthServiceClient {
	return &riderAuthServiceClient{cc}
}

func (c *riderAuthServiceClient) RegisterRider(ctx context.Context, in *RiderRegisterRequest, opts ...grpc.CallOption) (*RiderAuthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RiderAuthResponse)
	err := c.cc.Invoke(ctx, RiderAuthService_RegisterRider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riderAuthServiceClient) LoginRider(ctx context.Context, in *RiderLoginRequest, opts ...grpc.CallOption) (*RiderAuthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RiderAuthResponse)
	err := c.cc.Invoke(ctx, RiderAuthService_LoginRider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riderAuthServiceClient) GetRiderInfo(ctx context.Context, in *GetRiderInfoRequest, opts ...grpc.CallOption) (*GetRiderInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRiderInfoResponse)
	err := c.cc.Invoke(ctx, RiderAuthService_GetRiderInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riderAuthServiceClient) LogoutRider(ctx context.Context, in *LogoutRiderRequest, opts ...grpc.CallOption) (*LogoutRiderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogoutRiderResponse)
	err := c.cc.Invoke(ctx, RiderAuthService_LogoutRider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riderAuthServiceClient) UpdatePasswordRider(ctx context.Context, in *UpdatePasswordRiderRequest, opts ...grpc.CallOption) (*UpdatePasswordRiderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdatePasswordRiderResponse)
	err := c.cc.Invoke(ctx, RiderAuthService_UpdatePasswordRider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RiderAuthServiceServer is the server API for RiderAuthService service.
// All implementations must embed UnimplementedRiderAuthServiceServer
// for forward compatibility.
type RiderAuthServiceServer interface {
	RegisterRider(context.Context, *RiderRegisterRequest) (*RiderAuthResponse, error)
	LoginRider(context.Context, *RiderLoginRequest) (*RiderAuthResponse, error)
	GetRiderInfo(context.Context, *GetRiderInfoRequest) (*GetRiderInfoResponse, error)
	LogoutRider(context.Context, *LogoutRiderRequest) (*LogoutRiderResponse, error)
	UpdatePasswordRider(context.Context, *UpdatePasswordRiderRequest) (*UpdatePasswordRiderResponse, error)
	mustEmbedUnimplementedRiderAuthServiceServer()
}

// UnimplementedRiderAuthServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRiderAuthServiceServer struct{}

func (UnimplementedRiderAuthServiceServer) RegisterRider(context.Context, *RiderRegisterRequest) (*RiderAuthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterRider not implemented")
}
func (UnimplementedRiderAuthServiceServer) LoginRider(context.Context, *RiderLoginRequest) (*RiderAuthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LoginRider not implemented")
}
func (UnimplementedRiderAuthServiceServer) GetRiderInfo(context.Context, *GetRiderInfoRequest) (*GetRiderInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRiderInfo not implemented")
}
func (UnimplementedRiderAuthServiceServer) LogoutRider(context.Context, *LogoutRiderRequest) (*LogoutRiderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LogoutRider not implemented")
}
func (UnimplementedRiderAuthServiceServer) UpdatePasswordRider(context.Context, *UpdatePasswordRiderRequest) (*UpdatePasswordRiderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdatePasswordRider not implemented")
}
func (UnimplementedRiderAuthServiceServer) mustEmbedUnimplementedRiderAuthServiceServer() {}
func (UnimplementedRiderAuthServiceServer) testEmbeddedByValue()                          {}

// UnsafeRiderAuthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RiderAuthServiceServer will
// result in compilation errors.
type UnsafeRiderAuthServiceServer interface {
	mustEmbedUnimplementedRiderAuthServiceServer()
}

func RegisterRiderAuthServiceServer(s grpc.ServiceRegistrar, srv RiderAuthServiceServer) {
	// If the following call panics, it indicates UnimplementedRiderAuthServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RiderAuthService_ServiceDesc, srv)
}

func _RiderAuthService_RegisterRider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RiderRegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiderAuthServiceServer).RegisterRider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RiderAuthService_RegisterRider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiderAuthServiceServer).RegisterRider(ctx, req.(*RiderRegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RiderAuthService_LoginRider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RiderLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiderAuthServiceServer).LoginRider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RiderAuthService_LoginRider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiderAuthServiceServer).LoginRider(ctx, req.(*RiderLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RiderAuthService_GetRiderInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRiderInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiderAuthServiceServer).GetRiderInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RiderAuthService_GetRiderInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiderAuthServiceServer).GetRiderInfo(ctx, req.(*GetRiderInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RiderAuthService_LogoutRider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogoutRiderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiderAuthServiceServer).LogoutRider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RiderAuthService_LogoutRider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiderAuthServiceServer).LogoutRider(ctx, req.(*LogoutRiderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RiderAuthService_UpdatePasswordRider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePasswordRiderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiderAuthServiceServer).UpdatePasswordRider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RiderAuthService_UpdatePasswordRider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiderAuthServiceServer).UpdatePasswordRider(ctx, req.(*UpdatePasswordRiderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RiderAuthService_ServiceDesc is the grpc.ServiceDesc for RiderAuthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RiderAuthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auth.RiderAuthService",
	HandlerType: (*RiderAuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterRider",
			Handler:    _RiderAuthService_RegisterRider_Handler,
		},
		{
			MethodName: "LoginRider",
			Handler:    _RiderAuthService_LoginRider_Handler,
		},
		{
			MethodName: "GetRiderInfo",
			Handler:    _RiderAuthService_GetRiderInfo_Handler,
		},
		{
			MethodName: "LogoutRider",
			Handler:    _RiderAuthService_LogoutRider_Handler,
		},
		{
			MethodName: "UpdatePasswordRider",
			Handler:    _RiderAuthService_UpdatePasswordRider_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth.proto",
}

const (
	DriverAuthService_LoginDriver_FullMethodName          = "/auth.DriverAuthService/LoginDriver"
	DriverAuthService_RegisterDriver_FullMethodName       = "/auth.DriverAuthService/RegisterDriver"
	DriverAuthService_GetDriverInfo_FullMethodName        = "/auth.DriverAuthService/GetDriverInfo"
	DriverAuthService_GetDriverCarInfo_FullMethodName     = "/auth.DriverAuthService/GetDriverCarInfo"
	DriverAuthService_LogoutDriver_FullMethodName         = "/auth.DriverAuthService/LogoutDriver"
	DriverAuthService_UpdatePasswordDriver_FullMethodName = "/auth.DriverAuthService/UpdatePasswordDriver"
)

// DriverAuthServiceClient is the client API for DriverAuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DriverAuthServiceClient interface {
	LoginDriver(ctx context.Context, in *DriverLoginRequest, opts ...grpc.CallOption) (*DriverAuthResponse, error)
	RegisterDriver(ctx context.Context, in *DriverRegisterRequest, opts ...grpc.CallOption) (*DriverAuthResponse, error)
	GetDriverInfo(ctx context.Context, in *GetDriverInfoRequest, opts ...grpc.CallOption) (*GetDriverInfoResponse, error)
	GetDriverCarInfo(ctx context.Context, in *GetDriverCarInfoRequest, opts ...grpc.CallOption) (*GetDriverCarInfoResponse, error)
	LogoutDriver(ctx context.Context, in *LogoutDriverRequest, opts ...grpc.CallOption) (*LogoutDriverResponse, error)
	UpdatePasswordDriver(ctx context.Context, in *UpdatePasswordDriverRequest, opts ...grpc.CallOption) (*UpdatePasswordDriverResponse, error)
}

type driverAuthServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDriverAuthServiceClient(cc grpc.ClientConnInterface) DriverAuthServiceClient {
	return &driverAuthServiceClient{cc}
}

func (c *driverAuthServiceClient) LoginDriver(ctx context.Context, in *DriverLoginRequest, opts ...grpc.CallOption) (*DriverAuthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DriverAuthResponse)
	err := c.cc.Invoke(ctx, DriverAuthService_LoginDriver_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverAuthServiceClient) RegisterDriver(ctx context.Context, in *DriverRegisterRequest, opts ...grpc.CallOption) (*DriverAuthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DriverAuthResponse)
	err := c.cc.Invoke(ctx, DriverAuthService_RegisterDriver_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverAuthServiceClient) GetDriverInfo(ctx context.Context, in *GetDriverInfoRequest, opts ...grpc.CallOption) (*GetDriverInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDriverInfoResponse)
	err := c.cc.Invoke(ctx, DriverAuthService_GetDriverInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverAuthServiceClient) GetDriverCarInfo(ctx context.Context, in *GetDriverCarInfoRequest, opts ...grpc.CallOption) (*GetDriverCarInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDriverCarInfoResponse)
	err := c.cc.Invoke(ctx, DriverAuthService_GetDriverCarInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverAuthServiceClient) LogoutDriver(ctx context.Context, in *LogoutDriverRequest, opts ...grpc.CallOption) (*LogoutDriverResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogoutDriverResponse)
	err := c.cc.Invoke(ctx, DriverAuthService_LogoutDriver_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverAuthServiceClient) UpdatePasswordDriver(ctx context.Context, in *UpdatePasswordDriverRequest, opts ...grpc.CallOption) (*UpdatePasswordDriverResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdatePasswordDriverResponse)
	err := c.cc.Invoke(ctx, DriverAuthService_UpdatePasswordDriver_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DriverAuthServiceServer is the server API for DriverAuthService service.
// All implementations must embed UnimplementedDriverAuthServiceServer
// for forward compatibility.
type DriverAuthServiceServer interface {
	LoginDriver(context.Context, *DriverLoginRequest) (*DriverAuthResponse, error)
	RegisterDriver(context.Context, *DriverRegisterRequest) (*DriverAuthResponse, error)
	GetDriverInfo(context.Context, *GetDriverInfoRequest) (*GetDriverInfoResponse, error)
	GetDriverCarInfo(context.Context, *GetDriverCarInfoRequest) (*GetDriverCarInfoResponse, error)
	LogoutDriver(context.Context, *LogoutDriverRequest) (*LogoutDriverResponse, error)
	UpdatePasswordDriver(context.Context, *UpdatePasswordDriverRequest) (*UpdatePasswordDriverResponse, error)
	mustEmbedUnimplementedDriverAuthServiceServer()
}

// UnimplementedDriverAuthServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDriverAuthServiceServer struct{}

func (UnimplementedDriverAuthServiceServer) LoginDriver(context.Context, *DriverLoginRequest) (*DriverAuthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LoginDriver not implemented")
}
func (UnimplementedDriverAuthServiceServer) RegisterDriver(context.Context, *DriverRegisterRequest) (*DriverAuthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterDriver not implemented")
}
func (UnimplementedDriverAuthServiceServer) GetDriverInfo(context.Context, *GetDriverInfoRequest) (*GetDriverInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDriverInfo not implemented")
}
func (UnimplementedDriverAuthServiceServer) GetDriverCarInfo(context.Context, *GetDriverCarInfoRequest) (*GetDriverCarInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDriverCarInfo not implemented")
}
func (UnimplementedDriverAuthServiceServer) LogoutDriver(context.Context, *LogoutDriverRequest) (*LogoutDriverResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LogoutDriver not implemented")
}
func (UnimplementedDriverAuthServiceServer) UpdatePasswordDriver(context.Context, *UpdatePasswordDriverRequest) (*UpdatePasswordDriverResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdatePasswordDriver not implemented")
}
func (UnimplementedDriverAuthServiceServer) mustEmbedUnimplementedDriverAuthServiceServer() {}
func (UnimplementedDriverAuthServiceServer) testEmbeddedByValue()                           {}

// UnsafeDriverAuthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DriverAuthServiceServer will
// result in compilation errors.
type UnsafeDriverAuthServiceServer interface {
	mustEmbedUnimplementedDriverAuthServiceServer()
}

func RegisterDriverAuthServiceServer(s grpc.ServiceRegistrar, srv DriverAuthServiceServer) {
	// If the following call panics, it indicates UnimplementedDriverAuthServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DriverAuthService_ServiceDesc, srv)
}

func _DriverAuthService_LoginDriver_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DriverLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverAuthServiceServer).LoginDriver(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverAuthService_LoginDriver_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverAuthServiceServer).LoginDriver(ctx, req.(*DriverLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverAuthService_RegisterDriver_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DriverRegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverAuthServiceServer).RegisterDriver(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverAuthService_RegisterDriver_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverAuthServiceServer).RegisterDriver(ctx, req.(*DriverRegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverAuthService_GetDriverInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDriverInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverAuthServiceServer).GetDriverInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverAuthService_GetDriverInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverAuthServiceServer).GetDriverInfo(ctx, req.(*GetDriverInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverAuthService_GetDriverCarInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDriverCarInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverAuthServiceServer).GetDriverCarInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverAuthService_GetDriverCarInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverAuthServiceServer).GetDriverCarInfo(ctx, req.(*GetDriverCarInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverAuthService_LogoutDriver_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogoutDriverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverAuthServiceServer).LogoutDriver(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverAuthService_LogoutDriver_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverAuthServiceServer).LogoutDriver(ctx, req.(*LogoutDriverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverAuthService_UpdatePasswordDriver_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePasswordDriverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverAuthServiceServer).UpdatePasswordDriver(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverAuthService_UpdatePasswordDriver_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverAuthServiceServer).UpdatePasswordDriver(ctx, req.(*UpdatePasswordDriverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DriverAuthService_ServiceDesc is the grpc.ServiceDesc for DriverAuthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DriverAuthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auth.DriverAuthService",
	HandlerType: (*DriverAuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LoginDriver",
			Handler:    _DriverAuthService_LoginDriver_Handler,
		},
		{
			MethodName: "RegisterDriver",
			Handler:    _DriverAuthService_RegisterDriver_Handler,
		},
		{
			MethodName: "GetDriverInfo",
			Handler:    _DriverAuthService_GetDriverInfo_Handler,
		},
		{
			MethodName: "GetDriverCarInfo",
			Handler:    _DriverAuthService_GetDriverCarInfo_Handler,
		},
		{
			MethodName: "LogoutDriver",
			Handler:    _DriverAuthService_LogoutDriver_Handler,
		},
		{
			MethodName: "UpdatePasswordDriver",
			Handler:    _DriverAuthService_UpdatePasswordDriver_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth.proto",
}

const (
	HealthCheckService_CheckHealth_FullMethodName = "/auth.HealthCheckService/CheckHealth"
)

// HealthCheckServiceClient is the client API for HealthCheckService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HealthCheckServiceClient interface {
	CheckHealth(ctx context.Context, in *CheckHealthRequest, opts ...grpc.CallOption) (*CheckHealthRespone, error)
}

type healthCheckServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHealthCheckServiceClient(cc grpc.ClientConnInterface) HealthCheckServiceClient {
	return &healthCheckServiceClient{cc}
}

func (c *healthCheckServiceClient) CheckHealth(ctx context.Context, in *CheckHealthRequest, opts ...grpc.CallOption) (*CheckHealthRespone, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckHealthRespone)
	err := c.cc.Invoke(ctx, HealthCheckService_CheckHealth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HealthCheckServiceServer is the server API for HealthCheckService service.
// All implementations must embed UnimplementedHealthCheckServiceServer
// for forward compatibility.
type HealthCheckServiceServer interface {
	CheckHealth(context.Context, *CheckHealthRequest) (*CheckHealthRespone, error)
	mustEmbedUnimplementedHealthCheckServiceServer()
}

// UnimplementedHealthCheckServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHealthCheckServiceServer struct{}

func (UnimplementedHealthCheckServiceServer) CheckHealth(context.Context, *CheckHealthRequest) (*CheckHealthRespone, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckHealth not implemented")
}
func (UnimplementedHealthCheckServiceServer) mustEmbedUnimplementedHealthCheckServiceServer() {}
func (UnimplementedHealthCheckServiceServer) testEmbeddedByValue()                            {}

// UnsafeHealthCheckServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HealthCheckServiceServer will
// result in compilation errors.
type UnsafeHealthCheckServiceServer interface {
	mustEmbedUnimplementedHealthCheckServiceServer()
}

func RegisterHealthCheckServiceServer(s grpc.ServiceRegistrar, srv HealthCheckServiceServer) {
	// If the following call panics, it indicates UnimplementedHealthCheckServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HealthCheckService_ServiceDesc, srv)
}

func _HealthCheckService_CheckHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckHealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthCheckServiceServer).CheckHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HealthCheckService_CheckHealth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthCheckServiceServer).CheckHealth(ctx, req.(*CheckHealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HealthCheckService_ServiceDesc is the grpc.ServiceDesc for HealthCheckService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HealthCheckService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auth.HealthCheckService",
	HandlerType: (*HealthCheckServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckHealth",
			Handler:    _HealthCheckService_CheckHealth_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth.proto",
}
