// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: payment.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServiceType int32

const (
	ServiceType_SERVICE_TYPE_UNSPECIFIED ServiceType = 0
	ServiceType_SERVICE_TYPE_ECONOMY     ServiceType = 1
	ServiceType_SERVICE_TYPE_COMFORT     ServiceType = 2
	ServiceType_SERVICE_TYPE_XL          ServiceType = 3
)

// Enum value maps for ServiceType.
var (
	ServiceType_name = map[int32]string{
		0: "SERVICE_TYPE_UNSPECIFIED",
		1: "SERVICE_TYPE_ECONOMY",
		2: "SERVICE_TYPE_COMFORT",
		3: "SERVICE_TYPE_XL",
	}
	ServiceType_value = map[string]int32{
		"SERVICE_TYPE_UNSPECIFIED": 0,
		"SERVICE_TYPE_ECONOMY":     1,
		"SERVICE_TYPE_COMFORT":     2,
		"SERVICE_TYPE_XL":          3,
	}
)

func (x ServiceType) Enum() *ServiceType {
	p := new(ServiceType)
	*p = x
	return p
}

func (x ServiceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServiceType) Descriptor() protoreflect.EnumDescriptor {
	return file_payment_proto_enumTypes[0].Descriptor()
}

func (ServiceType) Type() protoreflect.EnumType {
	return &file_payment_proto_enumTypes[0]
}

func (x ServiceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServiceType.Descriptor instead.
func (ServiceType) EnumDescriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{0}
}

type HealthCheckResponse_ServingStatus int32

const (
	HealthCheckResponse_UNKNOWN         HealthCheckResponse_ServingStatus = 0
	HealthCheckResponse_SERVING         HealthCheckResponse_ServingStatus = 1
	HealthCheckResponse_NOT_SERVING     HealthCheckResponse_ServingStatus = 2
	HealthCheckResponse_SERVICE_UNKNOWN HealthCheckResponse_ServingStatus = 3
)

// Enum value maps for HealthCheckResponse_ServingStatus.
var (
	HealthCheckResponse_ServingStatus_name = map[int32]string{
		0: "UNKNOWN",
		1: "SERVING",
		2: "NOT_SERVING",
		3: "SERVICE_UNKNOWN",
	}
	HealthCheckResponse_ServingStatus_value = map[string]int32{
		"UNKNOWN":         0,
		"SERVING":         1,
		"NOT_SERVING":     2,
		"SERVICE_UNKNOWN": 3,
	}
)

func (x HealthCheckResponse_ServingStatus) Enum() *HealthCheckResponse_ServingStatus {
	p := new(HealthCheckResponse_ServingStatus)
	*p = x
	return p
}

func (x HealthCheckResponse_ServingStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthCheckResponse_ServingStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_payment_proto_enumTypes[1].Descriptor()
}

func (HealthCheckResponse_ServingStatus) Type() protoreflect.EnumType {
	return &file_payment_proto_enumTypes[1]
}

func (x HealthCheckResponse_ServingStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthCheckResponse_ServingStatus.Descriptor instead.
func (HealthCheckResponse_ServingStatus) EnumDescriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{10, 0}
}

type GeoLocation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      float64                `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeoLocation) Reset() {
	*x = GeoLocation{}
	mi := &file_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeoLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeoLocation) ProtoMessage() {}

func (x *GeoLocation) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeoLocation.ProtoReflect.Descriptor instead.
func (*GeoLocation) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{0}
}

func (x *GeoLocation) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *GeoLocation) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *GeoLocation) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type FareDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AmountInCents int64                  `protobuf:"varint,1,opt,name=amount_in_cents,json=amountInCents,proto3" json:"amount_in_cents,omitempty"`
	Currency      string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FareDetails) Reset() {
	*x = FareDetails{}
	mi := &file_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FareDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FareDetails) ProtoMessage() {}

func (x *FareDetails) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FareDetails.ProtoReflect.Descriptor instead.
func (*FareDetails) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{1}
}

func (x *FareDetails) GetAmountInCents() int64 {
	if x != nil {
		return x.AmountInCents
	}
	return 0
}

func (x *FareDetails) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type RideDetails struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DurationSeconds int64                  `protobuf:"varint,1,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	DistanceMetrs   int64                  `protobuf:"varint,2,opt,name=distance_metrs,json=distanceMetrs,proto3" json:"distance_metrs,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RideDetails) Reset() {
	*x = RideDetails{}
	mi := &file_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RideDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RideDetails) ProtoMessage() {}

func (x *RideDetails) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RideDetails.ProtoReflect.Descriptor instead.
func (*RideDetails) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{2}
}

func (x *RideDetails) GetDurationSeconds() int64 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *RideDetails) GetDistanceMetrs() int64 {
	if x != nil {
		return x.DistanceMetrs
	}
	return 0
}

type CreateCheckoutSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RideDetails   *RideDetails           `protobuf:"bytes,1,opt,name=ride_details,json=rideDetails,proto3" json:"ride_details,omitempty"`
	ServiceType   ServiceType            `protobuf:"varint,2,opt,name=service_type,json=serviceType,proto3,enum=payment.ServiceType" json:"service_type,omitempty"`
	Pickup        *GeoLocation           `protobuf:"bytes,3,opt,name=pickup,proto3" json:"pickup,omitempty"`
	Dropoff       *GeoLocation           `protobuf:"bytes,4,opt,name=dropoff,proto3" json:"dropoff,omitempty"`
	Fare          *FareDetails           `protobuf:"bytes,5,opt,name=fare,proto3" json:"fare,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCheckoutSessionRequest) Reset() {
	*x = CreateCheckoutSessionRequest{}
	mi := &file_payment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCheckoutSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCheckoutSessionRequest) ProtoMessage() {}

func (x *CreateCheckoutSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCheckoutSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateCheckoutSessionRequest) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{3}
}

func (x *CreateCheckoutSessionRequest) GetRideDetails() *RideDetails {
	if x != nil {
		return x.RideDetails
	}
	return nil
}

func (x *CreateCheckoutSessionRequest) GetServiceType() ServiceType {
	if x != nil {
		return x.ServiceType
	}
	return ServiceType_SERVICE_TYPE_UNSPECIFIED
}

func (x *CreateCheckoutSessionRequest) GetPickup() *GeoLocation {
	if x != nil {
		return x.Pickup
	}
	return nil
}

func (x *CreateCheckoutSessionRequest) GetDropoff() *GeoLocation {
	if x != nil {
		return x.Dropoff
	}
	return nil
}

func (x *CreateCheckoutSessionRequest) GetFare() *FareDetails {
	if x != nil {
		return x.Fare
	}
	return nil
}

type CreateCheckoutSessionResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CheckoutUrl     string                 `protobuf:"bytes,1,opt,name=checkout_url,json=checkoutUrl,proto3" json:"checkout_url,omitempty"`
	StripeSessionId string                 `protobuf:"bytes,2,opt,name=stripe_session_id,json=stripeSessionId,proto3" json:"stripe_session_id,omitempty"`
	TemporaryRideId string                 `protobuf:"bytes,3,opt,name=temporary_ride_id,json=temporaryRideId,proto3" json:"temporary_ride_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateCheckoutSessionResponse) Reset() {
	*x = CreateCheckoutSessionResponse{}
	mi := &file_payment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCheckoutSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCheckoutSessionResponse) ProtoMessage() {}

func (x *CreateCheckoutSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCheckoutSessionResponse.ProtoReflect.Descriptor instead.
func (*CreateCheckoutSessionResponse) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{4}
}

func (x *CreateCheckoutSessionResponse) GetCheckoutUrl() string {
	if x != nil {
		return x.CheckoutUrl
	}
	return ""
}

func (x *CreateCheckoutSessionResponse) GetStripeSessionId() string {
	if x != nil {
		return x.StripeSessionId
	}
	return ""
}

func (x *CreateCheckoutSessionResponse) GetTemporaryRideId() string {
	if x != nil {
		return x.TemporaryRideId
	}
	return ""
}

type PaymentSuccessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fare          *FareDetails           `protobuf:"bytes,1,opt,name=fare,proto3" json:"fare,omitempty"`
	RiderId       string                 `protobuf:"bytes,2,opt,name=rider_id,json=riderId,proto3" json:"rider_id,omitempty"`
	Pickup        *GeoLocation           `protobuf:"bytes,3,opt,name=pickup,proto3" json:"pickup,omitempty"`
	Dropoff       *GeoLocation           `protobuf:"bytes,4,opt,name=dropoff,proto3" json:"dropoff,omitempty"`
	TempRideId    string                 `protobuf:"bytes,5,opt,name=temp_ride_id,json=tempRideId,proto3" json:"temp_ride_id,omitempty"`
	RideDetails   *RideDetails           `protobuf:"bytes,6,opt,name=ride_details,json=rideDetails,proto3" json:"ride_details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentSuccessRequest) Reset() {
	*x = PaymentSuccessRequest{}
	mi := &file_payment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentSuccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentSuccessRequest) ProtoMessage() {}

func (x *PaymentSuccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentSuccessRequest.ProtoReflect.Descriptor instead.
func (*PaymentSuccessRequest) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{5}
}

func (x *PaymentSuccessRequest) GetFare() *FareDetails {
	if x != nil {
		return x.Fare
	}
	return nil
}

func (x *PaymentSuccessRequest) GetRiderId() string {
	if x != nil {
		return x.RiderId
	}
	return ""
}

func (x *PaymentSuccessRequest) GetPickup() *GeoLocation {
	if x != nil {
		return x.Pickup
	}
	return nil
}

func (x *PaymentSuccessRequest) GetDropoff() *GeoLocation {
	if x != nil {
		return x.Dropoff
	}
	return nil
}

func (x *PaymentSuccessRequest) GetTempRideId() string {
	if x != nil {
		return x.TempRideId
	}
	return ""
}

func (x *PaymentSuccessRequest) GetRideDetails() *RideDetails {
	if x != nil {
		return x.RideDetails
	}
	return nil
}

type PaymentSuccessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentSuccessResponse) Reset() {
	*x = PaymentSuccessResponse{}
	mi := &file_payment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentSuccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentSuccessResponse) ProtoMessage() {}

func (x *PaymentSuccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentSuccessResponse.ProtoReflect.Descriptor instead.
func (*PaymentSuccessResponse) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{6}
}

type PaymentFailedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fare          *FareDetails           `protobuf:"bytes,1,opt,name=fare,proto3" json:"fare,omitempty"`
	ServiceType   ServiceType            `protobuf:"varint,2,opt,name=service_type,json=serviceType,proto3,enum=payment.ServiceType" json:"service_type,omitempty"`
	Pickup        *GeoLocation           `protobuf:"bytes,3,opt,name=pickup,proto3" json:"pickup,omitempty"`
	Dropoff       *GeoLocation           `protobuf:"bytes,4,opt,name=dropoff,proto3" json:"dropoff,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentFailedRequest) Reset() {
	*x = PaymentFailedRequest{}
	mi := &file_payment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentFailedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentFailedRequest) ProtoMessage() {}

func (x *PaymentFailedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentFailedRequest.ProtoReflect.Descriptor instead.
func (*PaymentFailedRequest) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{7}
}

func (x *PaymentFailedRequest) GetFare() *FareDetails {
	if x != nil {
		return x.Fare
	}
	return nil
}

func (x *PaymentFailedRequest) GetServiceType() ServiceType {
	if x != nil {
		return x.ServiceType
	}
	return ServiceType_SERVICE_TYPE_UNSPECIFIED
}

func (x *PaymentFailedRequest) GetPickup() *GeoLocation {
	if x != nil {
		return x.Pickup
	}
	return nil
}

func (x *PaymentFailedRequest) GetDropoff() *GeoLocation {
	if x != nil {
		return x.Dropoff
	}
	return nil
}

type PaymentFailedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentFailedResponse) Reset() {
	*x = PaymentFailedResponse{}
	mi := &file_payment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentFailedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentFailedResponse) ProtoMessage() {}

func (x *PaymentFailedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentFailedResponse.ProtoReflect.Descriptor instead.
func (*PaymentFailedResponse) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{8}
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_payment_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{9}
}

func (x *HealthCheckRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Status        HealthCheckResponse_ServingStatus `protobuf:"varint,1,opt,name=status,proto3,enum=payment.HealthCheckResponse_ServingStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_payment_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{10}
}

func (x *HealthCheckResponse) GetStatus() HealthCheckResponse_ServingStatus {
	if x != nil {
		return x.Status
	}
	return HealthCheckResponse_UNKNOWN
}

var File_payment_proto protoreflect.FileDescriptor

const file_payment_proto_rawDesc = "" +
	"\n" +
	"\rpayment.proto\x12\apayment\"a\n" +
	"\vGeoLocation\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\"Q\n" +
	"\vFareDetails\x12&\n" +
	"\x0famount_in_cents\x18\x01 \x01(\x03R\ramountInCents\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\"_\n" +
	"\vRideDetails\x12)\n" +
	"\x10duration_seconds\x18\x01 \x01(\x03R\x0fdurationSeconds\x12%\n" +
	"\x0edistance_metrs\x18\x02 \x01(\x03R\rdistanceMetrs\"\x98\x02\n" +
	"\x1cCreateCheckoutSessionRequest\x127\n" +
	"\fride_details\x18\x01 \x01(\v2\x14.payment.RideDetailsR\vrideDetails\x127\n" +
	"\fservice_type\x18\x02 \x01(\x0e2\x14.payment.ServiceTypeR\vserviceType\x12,\n" +
	"\x06pickup\x18\x03 \x01(\v2\x14.payment.GeoLocationR\x06pickup\x12.\n" +
	"\adropoff\x18\x04 \x01(\v2\x14.payment.GeoLocationR\adropoff\x12(\n" +
	"\x04fare\x18\x05 \x01(\v2\x14.payment.FareDetailsR\x04fare\"\x9a\x01\n" +
	"\x1dCreateCheckoutSessionResponse\x12!\n" +
	"\fcheckout_url\x18\x01 \x01(\tR\vcheckoutUrl\x12*\n" +
	"\x11stripe_session_id\x18\x02 \x01(\tR\x0fstripeSessionId\x12*\n" +
	"\x11temporary_ride_id\x18\x03 \x01(\tR\x0ftemporaryRideId\"\x95\x02\n" +
	"\x15PaymentSuccessRequest\x12(\n" +
	"\x04fare\x18\x01 \x01(\v2\x14.payment.FareDetailsR\x04fare\x12\x19\n" +
	"\brider_id\x18\x02 \x01(\tR\ariderId\x12,\n" +
	"\x06pickup\x18\x03 \x01(\v2\x14.payment.GeoLocationR\x06pickup\x12.\n" +
	"\adropoff\x18\x04 \x01(\v2\x14.payment.GeoLocationR\adropoff\x12 \n" +
	"\ftemp_ride_id\x18\x05 \x01(\tR\n" +
	"tempRideId\x127\n" +
	"\fride_details\x18\x06 \x01(\v2\x14.payment.RideDetailsR\vrideDetails\"\x18\n" +
	"\x16PaymentSuccessResponse\"\xd7\x01\n" +
	"\x14PaymentFailedRequest\x12(\n" +
	"\x04fare\x18\x01 \x01(\v2\x14.payment.FareDetailsR\x04fare\x127\n" +
	"\fservice_type\x18\x02 \x01(\x0e2\x14.payment.ServiceTypeR\vserviceType\x12,\n" +
	"\x06pickup\x18\x03 \x01(\v2\x14.payment.GeoLocationR\x06pickup\x12.\n" +
	"\adropoff\x18\x04 \x01(\v2\x14.payment.GeoLocationR\adropoff\"\x17\n" +
	"\x15PaymentFailedResponse\"7\n" +
	"\x12HealthCheckRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\"\xaa\x01\n" +
	"\x13HealthCheckResponse\x12B\n" +
	"\x06status\x18\x01 \x01(\x0e2*.payment.HealthCheckResponse.ServingStatusR\x06status\"O\n" +
	"\rServingStatus\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aSERVING\x10\x01\x12\x0f\n" +
	"\vNOT_SERVING\x10\x02\x12\x13\n" +
	"\x0fSERVICE_UNKNOWN\x10\x03*t\n" +
	"\vServiceType\x12\x1c\n" +
	"\x18SERVICE_TYPE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14SERVICE_TYPE_ECONOMY\x10\x01\x12\x18\n" +
	"\x14SERVICE_TYPE_COMFORT\x10\x02\x12\x13\n" +
	"\x0fSERVICE_TYPE_XL\x10\x032\x9b\x02\n" +
	"\x0ePaymentService\x12f\n" +
	"\x15CreateCheckoutSession\x12%.payment.CreateCheckoutSessionRequest\x1a&.payment.CreateCheckoutSessionResponse\x12Q\n" +
	"\x0ePaymentSuccess\x12\x1e.payment.PaymentSuccessRequest\x1a\x1f.payment.PaymentSuccessResponse\x12N\n" +
	"\rPaymentFailed\x12\x1d.payment.PaymentFailedRequest\x1a\x1e.payment.PaymentFailedResponse2X\n" +
	"\x12HealthCheckService\x12B\n" +
	"\x05Check\x12\x1b.payment.HealthCheckRequest\x1a\x1c.payment.HealthCheckResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_payment_proto_rawDescOnce sync.Once
	file_payment_proto_rawDescData []byte
)

func file_payment_proto_rawDescGZIP() []byte {
	file_payment_proto_rawDescOnce.Do(func() {
		file_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payment_proto_rawDesc), len(file_payment_proto_rawDesc)))
	})
	return file_payment_proto_rawDescData
}

var file_payment_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_payment_proto_goTypes = []any{
	(ServiceType)(0),                       // 0: payment.ServiceType
	(HealthCheckResponse_ServingStatus)(0), // 1: payment.HealthCheckResponse.ServingStatus
	(*GeoLocation)(nil),                    // 2: payment.GeoLocation
	(*FareDetails)(nil),                    // 3: payment.FareDetails
	(*RideDetails)(nil),                    // 4: payment.RideDetails
	(*CreateCheckoutSessionRequest)(nil),   // 5: payment.CreateCheckoutSessionRequest
	(*CreateCheckoutSessionResponse)(nil),  // 6: payment.CreateCheckoutSessionResponse
	(*PaymentSuccessRequest)(nil),          // 7: payment.PaymentSuccessRequest
	(*PaymentSuccessResponse)(nil),         // 8: payment.PaymentSuccessResponse
	(*PaymentFailedRequest)(nil),           // 9: payment.PaymentFailedRequest
	(*PaymentFailedResponse)(nil),          // 10: payment.PaymentFailedResponse
	(*HealthCheckRequest)(nil),             // 11: payment.HealthCheckRequest
	(*HealthCheckResponse)(nil),            // 12: payment.HealthCheckResponse
}
var file_payment_proto_depIdxs = []int32{
	4,  // 0: payment.CreateCheckoutSessionRequest.ride_details:type_name -> payment.RideDetails
	0,  // 1: payment.CreateCheckoutSessionRequest.service_type:type_name -> payment.ServiceType
	2,  // 2: payment.CreateCheckoutSessionRequest.pickup:type_name -> payment.GeoLocation
	2,  // 3: payment.CreateCheckoutSessionRequest.dropoff:type_name -> payment.GeoLocation
	3,  // 4: payment.CreateCheckoutSessionRequest.fare:type_name -> payment.FareDetails
	3,  // 5: payment.PaymentSuccessRequest.fare:type_name -> payment.FareDetails
	2,  // 6: payment.PaymentSuccessRequest.pickup:type_name -> payment.GeoLocation
	2,  // 7: payment.PaymentSuccessRequest.dropoff:type_name -> payment.GeoLocation
	4,  // 8: payment.PaymentSuccessRequest.ride_details:type_name -> payment.RideDetails
	3,  // 9: payment.PaymentFailedRequest.fare:type_name -> payment.FareDetails
	0,  // 10: payment.PaymentFailedRequest.service_type:type_name -> payment.ServiceType
	2,  // 11: payment.PaymentFailedRequest.pickup:type_name -> payment.GeoLocation
	2,  // 12: payment.PaymentFailedRequest.dropoff:type_name -> payment.GeoLocation
	1,  // 13: payment.HealthCheckResponse.status:type_name -> payment.HealthCheckResponse.ServingStatus
	5,  // 14: payment.PaymentService.CreateCheckoutSession:input_type -> payment.CreateCheckoutSessionRequest
	7,  // 15: payment.PaymentService.PaymentSuccess:input_type -> payment.PaymentSuccessRequest
	9,  // 16: payment.PaymentService.PaymentFailed:input_type -> payment.PaymentFailedRequest
	11, // 17: payment.HealthCheckService.Check:input_type -> payment.HealthCheckRequest
	6,  // 18: payment.PaymentService.CreateCheckoutSession:output_type -> payment.CreateCheckoutSessionResponse
	8,  // 19: payment.PaymentService.PaymentSuccess:output_type -> payment.PaymentSuccessResponse
	10, // 20: payment.PaymentService.PaymentFailed:output_type -> payment.PaymentFailedResponse
	12, // 21: payment.HealthCheckService.Check:output_type -> payment.HealthCheckResponse
	18, // [18:22] is the sub-list for method output_type
	14, // [14:18] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_payment_proto_init() }
func file_payment_proto_init() {
	if File_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payment_proto_rawDesc), len(file_payment_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_payment_proto_goTypes,
		DependencyIndexes: file_payment_proto_depIdxs,
		EnumInfos:         file_payment_proto_enumTypes,
		MessageInfos:      file_payment_proto_msgTypes,
	}.Build()
	File_payment_proto = out.File
	file_payment_proto_goTypes = nil
	file_payment_proto_depIdxs = nil
}
